### ISSUE TITLE
Tasklist's localizations regular updates

### ISSUE THREAD

**Issue by AnatolyKostrikov** [camunda/camunda-webapp-translations#162]
It is an idea to update Tasklist's translation JSONs up to [an actual](https://github.com/camunda/camunda-webapp-translations#list-of-available-translations) version using the **English translation** files as a [master copy](https://github.com/camunda/camunda-bpm-platform/tree/7.18.0/webapps/ui/tasklist/client/en.json).

Previous issues on a localization topic:
- https://confluence.camunda.com/display/AP/Performing+a+Minor+Release#PerformingaMinorRelease-UpdategermanWebapptranslations
- https://github.com/camunda/camunda-bpm-platform/issues/2992#event-7932763665
- https://github.com/camunda/camunda-bpm-platform/issues/2897

**Comment by tasso94** [comment]
Please use the issue tracker in our main repository: https://github.com/camunda/camunda-bpm-platform/issues
